import type { Metadata } from 'next';

export const siteConfig = {
  name: 'Sadik Studio',
  fullName: 'Sadik Shaikh',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://sadikstudio.in',
  title:
    'Sadik Studio — Founder-Led React, SaaS, Shopify & AI Development',
  description:
    'Sadik Studio is a founder-led development practice led by Sadik Shaikh (6+ years). We ship React, Next.js, Shopify, and SaaS products with AI-powered features for startups in the USA, UK, Australia & India. Shopify from $2,000. SaaS MVPs from $10,000.',
  keywords: [
    'hire react developer',
    'hire next.js developer',
    'hire shopify developer',
    'hire saas developer',
    'hire ai developer',
    'react developer india',
    'react developer usa',
    'react developer uk',
    'react developer australia',
    'shopify developer india',
    'shopify developer usa',
    'shopify developer uk',
    'saas developer india',
    'saas developer usa',
    'saas developer uk',
    'saas developer australia',
    'custom saas development',
    'custom web app development',
    'headless shopify developer',
    'ai web app development services',
    'saas development with ai integration',
    'openai integration for saas',
    'rag pipeline developer for hire',
    'founder-led development studio',
    'react development studio',
  ],
  locale: 'en_US',
  twitterHandle: '@sadikdev',
  author: 'Sadik Shaikh',
} as const;

interface BuildMetadataParams {
  title?: string;
  description?: string;
  path?: string;
  keywords?: readonly string[] | string[];
  images?: string[];
  noIndex?: boolean;
}

/**
 * Build a Next.js Metadata object with consistent defaults.
 * Title is composed as "{title} | Sadik" unless it already contains the brand.
 */
export function buildMetadata({
  title,
  description,
  path = '/',
  keywords,
  images,
  noIndex = false,
}: BuildMetadataParams = {}): Metadata {
  const composedTitle = title
    ? title.includes(siteConfig.name)
      ? title
      : `${title} | ${siteConfig.name}`
    : siteConfig.title;

  const composedDescription = description ?? siteConfig.description;
  const url = `${siteConfig.url}${path}`;
  // Default OG image is auto-generated by app/opengraph-image.tsx (Next.js
  // metadata file convention). Only set explicit images when the caller
  // passes custom ones — otherwise Next.js auto-wires the dynamic default.
  const ogImages = images && images.length ? images : undefined;

  return {
    title: composedTitle,
    description: composedDescription,
    keywords: (keywords ?? siteConfig.keywords) as string[],
    authors: [{ name: siteConfig.author }],
    creator: siteConfig.author,
    metadataBase: new URL(siteConfig.url),
    alternates: { canonical: url },
    verification: {
      // Google Search Console verification (typed field → google-site-verification meta)
      google: 'zdJkkaQ-6FQMCiZxo26dNrUrZELDvvas1o0ySlm2F3E',
      other: {
        // Bing Webmaster Tools site verification
        'msvalidate.01': '895133D1B0D1CB306691473722082FDA',
        // Ahrefs Site Audit verification
        'ahrefs-site-verification':
          '8f04923d9055a7089dbbae1d407bc83ebac027d9db83103e1633a58b307252fd',
      },
    },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            'max-image-preview': 'large',
            'max-snippet': -1,
          },
        },
    openGraph: {
      type: 'website',
      locale: siteConfig.locale,
      url,
      siteName: siteConfig.name,
      title: composedTitle,
      description: composedDescription,
      ...(ogImages && {
        images: ogImages.map((img) => ({ url: img, width: 1200, height: 630 })),
      }),
    },
    twitter: {
      card: 'summary_large_image',
      title: composedTitle,
      description: composedDescription,
      creator: siteConfig.twitterHandle,
      ...(ogImages && { images: ogImages }),
    },
  };
}
